/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testSimpleMonteCarlo1() {
        var classUnderTest = new App();
        var expiry = 0.5;
        var strike = 100;
        var spot = 100;
        var vol = 0.2;
        var r = 0.05;
        var numPaths = 100000;
        var result = classUnderTest.simpleMonteCarlo1(expiry, strike, spot, vol, r, numPaths);
        // assertEquals(result, 100, 0.01);
        System.out.println(result);
    }
}
